sensor:
  - platform: mqtt
    name: Fingerprint Sensor 1
    icon: 'hass:fingerprint'
    availability_topic: "fingerprint_sensor/1/available"
    state_topic: "fingerprint_sensor/1/state"
    json_attributes_topic: "fingerprint_sensor/1/attributes"
